[package]
name = "rust-hello-world"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust-hello-world"
path = "src/main.rs"

[[bin]]
name = "migrate"
path = "src/bin/migrate.rs"

[dependencies]
actix-web    = "4"
tokio        = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
serde_json   = "1"
